stages:
  - deploy
  - test

.base-url:
  only:
    variables:
      - $BASE_URL

.default-variables-saucelabs:
  variables:
    DRIVER: SauceLabs
    BROWSER_VERSION: latest
    PLATFORM: Windows 10
    MARK_EXPRESSION: not headless and not download
    TEST_IMAGE: mozmeao/bedrock_test:8bc39f22cd300b333d5c65af1e883c9532653754
    PYTEST_PROCESSES: "4"

.default-variables-remote:
  extends: .default-variables-saucelabs
  variables:
    DRIVER: Remote
    PYTEST_PROCESSES: "auto"
    PLATFORM: Linux

.deploy:
  script:
    - kubectl apply -f ${DEPLOYMENT}
    - bin/rollout-status.sh ${DEPLOYMENT}
  stage: deploy
  tags:
    - iowa-c # shell runner with iowa-a.kubeconfig via IAM role
  variables:
    KUBECONFIG: /home/gitlab-runner/.kube/iowa-a.kubeconfig
  retry: 2

.dev:
  only:
    changes:
      - "iowa-a/bedrock-dev/*"
    refs:
      - master
      - gitlab-ci-dev
    variables:
      - $CI_PIPELINE_SOURCE == "push"
  variables:
    BASE_URL: https://bedrock-dev.gcp.moz.works
    DEPLOYMENT: iowa-a/bedrock-dev
    KUBECONFIG: /home/gitlab-runner/.kube/iowa-a.kubeconfig

.prod-frankfurt:
  only:
    changes:
      - "frankfurt/bedrock-prod/*"
    refs:
      - master
    variables:
      - $CI_PIPELINE_SOURCE == "push"
  tags:
    - mozmeao
    - aws
  variables:
    BASE_URL: https://bedrock-prod.frankfurt.moz.works
    DEPLOYMENT: frankfurt/bedrock-prod
    KUBECONFIG: /home/gitlab-runner/.kube/frankfurt.kubeconfig

.oregon-b-test:
  only:
    changes:
      - "oregon-b/bedrock-test/*"
    refs:
      - master
      - bedrock-test
    variables:
      - $CI_PIPELINE_SOURCE == "push"
  tags:
    - mozmeao
    - aws
  variables:
    BASE_URL: https://bedrock-test.moz.works
    DEPLOYMENT: oregon-b/bedrock-test
    KUBECONFIG: /home/gitlab-runner/.kube/oregon-b.kubeconfig

.prod-iowa-a:
  only:
    changes:
      - "iowa-a/bedrock-prod/*"
    refs:
      - master
    variables:
      - $CI_PIPELINE_SOURCE == "push"
  variables:
    BASE_URL: https://bedrock-prod.gcp.moz.works
    DEPLOYMENT: iowa-a/bedrock-prod
    KUBECONFIG: /home/gitlab-runner/.kube/iowa-a.kubeconfig

.stage:
  only:
    changes:
      - "iowa-a/bedrock-stage/*"
    refs:
      - master
    variables:
      - $CI_PIPELINE_SOURCE == "push"
  variables:
    BASE_URL: https://bedrock-stage.gcp.moz.works
    DEPLOYMENT: iowa-a/bedrock-stage
    KUBECONFIG: /home/gitlab-runner/.kube/iowa-a.kubeconfig

.test-k8s:
  image: mozmeao/bedrock_test:8bc39f22cd300b333d5c65af1e883c9532653754
  script:
    - cd /app
    - bin/run-integration-tests.sh

.test:
  stage: test
  script: bin/acceptance-tests.sh
  tags:
    - mozmeao
    - aws
  after_script:
    - bin/cleanup_after_functional_tests.sh
  retry: 1

.test-chrome:
  extends:
    - .default-variables-remote
    - .test
  variables:
    BROWSER_NAME: chrome
    MARK_EXPRESSION: "$$MARK_EXPRESION and not skip_if_not_firefox"

.test-download:
  extends:
     - .default-variables-remote
     - .test
  variables:
    DRIVER: ""
    MARK_EXPRESSION: download

.test-firefox:
  extends:
    - .default-variables-remote
    - .test
  variables:
    BROWSER_NAME: firefox
    MARK_EXPRESSION: "$$MARK_EXPRESION and not skip_if_firefox"


.test-headless:
  extends:
    - .default-variables-remote
    - .test
  variables:
    DRIVER: ""
    MARK_EXPRESSION: headless

.test-edge:
  extends:
    - .default-variables-saucelabs
    - .test
  variables:
    BROWSER_NAME: MicrosoftEdge
    MARK_EXPRESSION: "$$MARK_EXPRESION and not skip_if_not_firefox"

.test-ie:
  extends:
    - .default-variables-saucelabs
    - .test
  variables:
    BROWSER_NAME: internet explorer
    MARK_EXPRESSION: "$$MARK_EXPERSSION and not skip_if_not_firefox and not skip_if_internet_explorer"

.test-ie9:
  extends:
    - .default-variables-saucelabs
    - .test
  variables:
    BROWSER_NAME: internet explorer
    BROWSER_VERSION: "9.0"
    PLATFORM: Windows 7
    MARK_EXPRESSION: sanity

base-url-test-chrome:
  extends:
    - .base-url
    - .test-chrome

base-url-test-download:
  extends:
    - .base-url
    - .test-download

base-url-test-firefox:
  extends:
    - .base-url
    - .test-firefox

base-url-test-headless:
  extends:
    - .base-url
    - .test-headless

base-url-test-ie:
  extends:
    - .base-url
    - .test-ie

dev-deploy:
  extends:
    - .dev
    - .deploy

dev-test-chrome:
  resource_group: dev-test-chrome
  extends:
    - .dev
    - .test-chrome

dev-test-firefox:
  resource_group: dev-test-firefox
  extends:
    - .dev
    - .test-firefox

dev-test-headless:
  resource_group: dev-test-headless
  extends:
    - .dev
    - .test-headless

dev-test-edge:
  resource_group: dev-test-edge
  extends:
    - .dev
    - .test-edge

dev-test-ie:
  resource_group: dev-test-ie
  extends:
    - .dev
    - .test-ie

oregon-b-test-deploy:
  extends:
    - .deploy
    - .oregon-b-test

oregon-b-test-chrome:
  resource_group: oregon-b-test-chrome
  extends:
    - .oregon-b-test
    - .test-chrome

oregon-b-test-download:
  resource_group: oregon-b-test-download
  extends:
    - .oregon-b-test
    - .test-download

oregon-b-test-firefox:
  resource_group: oregon-b-test-firefox
  extends:
    - .oregon-b-test
    - .test-firefox

oregon-b-test-headless:
  resource_group: oregon-b-test-headless
  extends:
    - .oregon-b-test
    - .test-headless

oregon-b-test-edge:
  resource_group: oregon-b-test-edge
  extends:
    - .oregon-b-test
    - .test-edge

oregon-b-test-ie:
  resource_group: oregon-b-test-ie
  extends:
    - .oregon-b-test
    - .test-ie

oregon-b-test-ie9:
  resource_group: oregon-b-test-ie9
  extends:
    - .oregon-b-test
    - .test-ie9

prod-frankfurt-deploy:
  extends:
    - .deploy
    - .prod-frankfurt  # needs to come second to override tags & variables

prod-frankfurt-test-headless:
  resource_group: prod-frankfurt-test-headless
  extends:
    - .test-headless
    - .prod-frankfurt

prod-iowa-a-deploy:
  extends:
    - .prod-iowa-a
    - .deploy

prod-iowa-a-test-chrome:
  resource_group: prod-iowa-a-test-chrome
  extends:
    - .prod-iowa-a
    - .test-chrome

prod-iowa-a-test-download:
  resource_group: prod-iowa-a-test-download
  extends:
    - .prod-iowa-a
    - .test-download

prod-iowa-a-test-firefox:
  resource_group: prod-iowa-a-test-firefox
  extends:
    - .prod-iowa-a
    - .test-firefox


prod-iowa-a-test-headless:
  resource_group: prod-iowa-a-test-headless
  extends:
    - .prod-iowa-a
    - .test-headless

prod-iowa-a-test-ie:
  resource_group: prod-iowa-a-test-ie
  extends:
    - .prod-iowa-a
    - .test-ie

prod-iowa-a-test-ie9:
  resource_group: prod-iowa-a-test-ie9
  extends:
    - .prod-iowa-a
    - .test-ie9

stage-deploy:
  extends:
    - .stage
    - .deploy

stage-test-chrome:
  resource_group: stage-test-chrome
  extends:
    - .stage
    - .test-chrome

stage-test-download:
  resource_group: stage-test-download
  extends:
    - .stage
    - .test-download

stage-test-firefox:
  resource_group: stage-test-firefox
  extends:
    - .stage
    - .test-firefox

stage-test-headless:
  resource_group: stage-test-headless
  extends:
    - .stage
    - .test-headless

stage-test-ie:
  resource_group: stage-test-ie
  extends:
    - .stage
    - .test-ie

stage-test-ie9:
  resource_group: stage-test-ie9
  extends:
    - .stage
    - .test-ie9
